# -*- coding:utf-8 -*-
import re
str = "My mobile phone number is 010-123-4567"
s = re.compile("(\d+)-(\d+)-(\d+)")
a,b,c = s.search(str).groups()
print(a,b,c, sep=',')
print(re.sub("\s", ":", str))
print(s.findall(str))
print('=================================')
telecheck = re.compile(r'(\d{2,3})-(\d{3,4})-(\d{4})')
a = bool(telecheck.match('02-123-4567'))
print("1:",a)
a = bool(telecheck.match('02-A123-4567'))
print("2:",a)
a = bool(telecheck.match('3402-123-4567'))
print("3:",a)
a = bool(telecheck.match('032-123-4567'))
print("4:",a)
print('=================================')
phone = re.compile(r'(\d{3})-(\d{3,4})-(\d{4})')
m=phone.match('010-123-4567')
print(m.groups())
print(m.group())
print((m.groups()[1], m.groups()[2]))
print('m.start(3):', m.start(3))
print('m.end(2):', m.end(2))
print(m.string[m.start(2):m.end(3)])
print(m.string)
print(m)

print(re.escape(r'*.txt'))