# Generated by Django 2.1.2 on 2018-10-17 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SungjukList',
            fields=[
                ('hakbun', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=10)),
                ('kor', models.IntegerField(blank=True)),
                ('eng', models.IntegerField(blank=True)),
                ('math', models.IntegerField(blank=True)),
                ('sum', models.IntegerField(blank=True)),
                ('avg', models.IntegerField(blank=True)),
                ('grade', models.CharField(blank=True, max_length=5)),
            ],
        ),
    ]
