# Generated by Django 2.1.2 on 2018-10-17 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sungjuklist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sungjuklist',
            name='hakbun',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
