# Generated by Django 2.1.2 on 2018-10-17 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sungjuklist', '0002_auto_20181017_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sungjuklist',
            name='avg',
            field=models.FloatField(blank=True),
        ),
    ]
