# -*- coding:utf-8 -*-
import re

m_str = 'matches the start of a string'
m = re.match('[a-z]+', m_str)
r = re.search('[a-z]+', m_str)
f = re.findall('[a-z]+', m_str)
print('m :', m)
print('r :', r)
print('f :', f)
print(re.search(".+", "\nbb"))

p = re.compile('[a-z]+')
m = p.match(m_str)
print("m :", m)

s=re.search('\\\\\w+', '\\banana')
print('s :', s)
q=re.search(r'\\\w+', r'\bana na')
print('q :', q)

a=re.search(r'\d+', 'abcd0123efgh')
print(a)
print("a.group() :",a.group())
print(a.start(), a.end())
print(re.findall('\d','abcd0123'))
print(re.findall('\d+','abcd0123'))
r=bool(re.match('ba', 'l like banana'))
print(r)
r=bool(re.search('ba', 'i like banana'))
print(r)
print('===================')
r=re.findall('a\w*', 'application a orange apple app banana')
print("* :",r)
r=re.findall('a\w+', 'application a orange apple app banana')
print("+ :",r)
r=re.findall('a\w?', 'application a orange apple app banana')
print("? :",r)
print('===================')
r=re.sub("-",".","123-456-789")
print(r)
r=re.sub("[:|]", ".", "a:b|c")
print(r)
r=re.sub("[:,|\s]", "_", "one:two\ntree|four", 2)
print(r)
print('===================')
r=re.findall('grape', 'grape apple GRAPE graPe', re.I)
print(r)
print('===================')
c=re.compile(r'app\w+')
res=c.findall("application a orange apple banana")
print(res)
print('===================')
pat=re.compile(r'(\w+)\s+(\d+)')
res=pat.findall('puppy 10 duck 20 cat 30 ')
print(res)
print('===================')
pat=re.compile(r'\w+\s+\d+')
res=pat.findall('puppy 10 duck 20 cat 30 ')
print(res)
print('===================')
a=re.search(r'(\d+)-(\d+)-(\d+)', '2016-12-25')
year, month, day = a.groups()
print(a)
print(year, month, day)
print(a.group(1), a.group(2), a.group(3))
print(a.group(0))
print(year)
print('===================')
p=re.compile(r'(\w+)\s+(?:\w+)\s(\w+)')
a=p.search('abc def ghi')
print(a.groups())
print('===================')
p=re.compile(r'(?P<word>\w+)\s(?P=word)')
a=p.search('python python')
print(a.group('word'))
print(a.group(0))
print(a.group(1))
print('===================')
p=re.compile(r'[a-z][a-z]')
a=p.findall("ab b1 c3 ad de d*")
print(a)

print('===================')
p= re.findall(r'[a-z]|[A-Z]', '1aBc')
print(p)
