f = open('text.txt', 'r', encoding='utf-8')
print('파일 현재 위치:', f.tell())
print(f.read())
print('파일 현재 위치:', f.tell())
print()
f.seek(0)
print('파일 현재 위치:', f.tell())
print(f.readline(), end='')
print('파일 현재 위치:', f.tell())
f.close()